package pdsu.dzyhap.dao;

import java.util.List;
import pdsu.dzyhap.bean.Base;

public interface BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer baseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int insert(Base record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    Base selectByPrimaryKey(Integer baseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    List<Base> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(Base record);
}