package pdsu.dzyhap.dao;

import java.util.List;
import pdsu.dzyhap.bean.Bat_info;

public interface Bat_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bat_info
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String batId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bat_info
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int insert(Bat_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bat_info
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    Bat_info selectByPrimaryKey(String batId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bat_info
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    List<Bat_info> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bat_info
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(Bat_info record);
}