package pdsu.dzyhap.dao;

import java.util.List;
import pdsu.dzyhap.bean.Bat_mat;

public interface Bat_matMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bat_mat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String batMatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bat_mat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int insert(Bat_mat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bat_mat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    Bat_mat selectByPrimaryKey(String batMatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bat_mat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    List<Bat_mat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bat_mat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(Bat_mat record);
}