package pdsu.dzyhap.dao;

import java.util.List;
import pdsu.dzyhap.bean.Danger_degree;

public interface Danger_degreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_degree
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer degreeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_degree
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int insert(Danger_degree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_degree
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    Danger_degree selectByPrimaryKey(Integer degreeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_degree
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    List<Danger_degree> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table danger_degree
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(Danger_degree record);
}