package pdsu.dzyhap.dao;

import java.sql.SQLException;
import java.util.List;

import org.apache.ibatis.annotations.Param;

import pdsu.dzyhap.bean.Dept;

public interface DeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    void deleteByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    Dept selectByPrimaryKey(Integer deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    List<Dept> selectAll();
    
	/**
	 * 根据id查询记录
	 * @param id
	 * @return
	 */
     Dept  selectById(int id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(Dept dept);
    
    //模糊查询

    List<Dept> SearchDept(@Param("deptId")Integer deptId,@Param("deptName")String deptName,
    		@Param("deptType")String deptType,@Param("deptRemark")String  deptRemark);
    
	
}