package pdsu.dzyhap.dao;

import java.util.List;
import pdsu.dzyhap.bean.Plan_mat;

public interface Plan_matMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_mat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String planMatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_mat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int insert(Plan_mat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_mat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    Plan_mat selectByPrimaryKey(String planMatId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_mat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    List<Plan_mat> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_mat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(Plan_mat record);
}