package pdsu.dzyhp.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import pdsu.dzyhp.bean.Base;

public interface BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer baseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int insert(Base record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    Base selectByPrimaryKey(Integer baseId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    List<Base> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(Base record);
    
    /**
     * 多表查询全部信息
     * @return
     */
	List<Base> query();
	
	/**
	 * 根据id查询一条数据
	 * @param baseId
	 * @return
	 */
	Base selectOne(Integer baseId);

	/**
	 * 根据账户名或者状态查询信息
	 * @param baseName
	 * @param stat
	 * @return
	 */
	List<Base> selectBybaseNameAndStat(@Param("baseName")String baseName,@Param("stat")String stat);
	
	
}