package pdsu.dzyhp.dao;

import java.util.List;

import pdsu.dzyhp.bean.Plan_info;

public interface Plan_infoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_info
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_info
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int insert(Plan_info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_info
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    Plan_info selectByPrimaryKey(String planId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_info
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    List<Plan_info> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table plan_info
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    int updateByPrimaryKey(Plan_info record);
}