package pdsu.dzyhap.bean;

public class Base {
   
    private Integer baseId;
    private String baseName;
    private String baseType;
    private Integer foundTypeId;
    private Integer deptId;
    private String userId;
    private String foundSrc;
    private String foundBudget;
    private String foundProj;
    private String foundDept;
    private String foundStat;
   
    private String baseStat;

    private String remark;

    public Integer getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.base_id
     *
     * @param baseId the value for base.base_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBaseId(Integer baseId) {
        this.baseId = baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.base_name
     *
     * @return the value of base.base_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getBaseName() {
        return baseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.base_name
     *
     * @param baseName the value for base.base_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBaseName(String baseName) {
        this.baseName = baseName == null ? null : baseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.base_type
     *
     * @return the value of base.base_type
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getBaseType() {
        return baseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.base_type
     *
     * @param baseType the value for base.base_type
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBaseType(String baseType) {
        this.baseType = baseType == null ? null : baseType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.found_type_id
     *
     * @return the value of base.found_type_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Integer getFoundTypeId() {
        return foundTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.found_type_id
     *
     * @param foundTypeId the value for base.found_type_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setFoundTypeId(Integer foundTypeId) {
        this.foundTypeId = foundTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.dept_id
     *
     * @return the value of base.dept_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.dept_id
     *
     * @param deptId the value for base.dept_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.user_id
     *
     * @return the value of base.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.user_id
     *
     * @param userId the value for base.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.found_src
     *
     * @return the value of base.found_src
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getFoundSrc() {
        return foundSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.found_src
     *
     * @param foundSrc the value for base.found_src
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setFoundSrc(String foundSrc) {
        this.foundSrc = foundSrc == null ? null : foundSrc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.found_budget
     *
     * @return the value of base.found_budget
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getFoundBudget() {
        return foundBudget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.found_budget
     *
     * @param foundBudget the value for base.found_budget
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setFoundBudget(String foundBudget) {
        this.foundBudget = foundBudget == null ? null : foundBudget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.found_proj
     *
     * @return the value of base.found_proj
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getFoundProj() {
        return foundProj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.found_proj
     *
     * @param foundProj the value for base.found_proj
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setFoundProj(String foundProj) {
        this.foundProj = foundProj == null ? null : foundProj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.found_dept
     *
     * @return the value of base.found_dept
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getFoundDept() {
        return foundDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.found_dept
     *
     * @param foundDept the value for base.found_dept
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setFoundDept(String foundDept) {
        this.foundDept = foundDept == null ? null : foundDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.found_stat
     *
     * @return the value of base.found_stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getFoundStat() {
        return foundStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.found_stat
     *
     * @param foundStat the value for base.found_stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setFoundStat(String foundStat) {
        this.foundStat = foundStat == null ? null : foundStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.base_stat
     *
     * @return the value of base.base_stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getBaseStat() {
        return baseStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.base_stat
     *
     * @param baseStat the value for base.base_stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBaseStat(String baseStat) {
        this.baseStat = baseStat == null ? null : baseStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.remark
     *
     * @return the value of base.remark
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.remark
     *
     * @param remark the value for base.remark
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}