package pdsu.dzyhap.bean;

public class Users {
    
	public Users() {
		// TODO Auto-generated constructor stub
	}
	
	
    public Users(String userId, String pwd, String name, String title, Dept dept, String stat, String statStr) {
		super();
		this.userId = userId;
		this.pwd = pwd;
		this.name = name;
		this.title = title;
		this.dept = dept;
		this.stat = stat;
		this.statStr = statStr;
	}


	private String userId;

   
    private String pwd;

   
    private String name;

    
    private String title;

    
//    private Integer deptId;
    private Dept dept;

    
    private String stat;

    private String statStr;
    
   
    public String getStatStr() {
		return statStr;
	}

	public void setStatStr(String statStr) {
		this.statStr = statStr;
	}

	public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.user_id
     *
     * @param userId the value for users.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.pwd
     *
     * @return the value of users.pwd
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.pwd
     *
     * @param pwd the value for users.pwd
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.name
     *
     * @return the value of users.name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.name
     *
     * @param name the value for users.name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.title
     *
     * @return the value of users.title
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.title
     *
     * @param title the value for users.title
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.dept_id
     *
     * @return the value of users.dept_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
  
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.stat
     *
     * @return the value of users.stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.stat
     *
     * @param stat the value for users.stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }

	public Dept getDept() {
		return dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	@Override
	public String toString() {
		return "Users [userId=" + userId + ", pwd=" + pwd + ", name=" + name + ", title=" + title + ", dept=" + dept
				+ ", stat=" + stat + ", statStr=" + statStr + "]";
	}

	
    
    
    
    
}