package pdsu.dzyhp.bean;

public class Base {
   
    private Integer baseId;
    private String baseName;
    private String baseType;
//    private Integer foundTypeId;
    private Found_type found_type;
//    private Integer deptId;
    private Dept dept;
//    private String userId;
    private Users users;
    private String foundSrc;
    private String foundBudget;
    private String foundProj;
    private String foundDept;
    private String foundStat;
   
    private String baseStat;

    private String baseStatString;
    
    
    
    public String getBaseStatString() {
		return baseStatString;
	}

	public void setBaseStatString(String baseStatString) {
		this.baseStatString = baseStatString;
	}



	private String remark;

    public Integer getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.base_id
     *
     * @param baseId the value for base.base_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBaseId(Integer baseId) {
        this.baseId = baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.base_name
     *
     * @return the value of base.base_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getBaseName() {
        return baseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.base_name
     *
     * @param baseName the value for base.base_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBaseName(String baseName) {
        this.baseName = baseName == null ? null : baseName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column base.base_type
     *
     * @return the value of base.base_type
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getBaseType() {
        return baseType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column base.base_type
     *
     * @param baseType the value for base.base_type
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBaseType(String baseType) {
        this.baseType = baseType == null ? null : baseType.trim();
    }

	public Found_type getFound_type() {
		return found_type;
	}

	public void setFound_type(Found_type found_type) {
		this.found_type = found_type;
	}

	public Dept getDept() {
		return dept;
	}

	public void setDept(Dept dept) {
		this.dept = dept;
	}

	public Users getUsers() {
		return users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getFoundSrc() {
		return foundSrc;
	}

	public void setFoundSrc(String foundSrc) {
		this.foundSrc = foundSrc;
	}

	public String getFoundBudget() {
		return foundBudget;
	}

	public void setFoundBudget(String foundBudget) {
		this.foundBudget = foundBudget;
	}

	public String getFoundProj() {
		return foundProj;
	}

	public void setFoundProj(String foundProj) {
		this.foundProj = foundProj;
	}

	public String getFoundDept() {
		return foundDept;
	}

	public void setFoundDept(String foundDept) {
		this.foundDept = foundDept;
	}

	public String getFoundStat() {
		return foundStat;
	}

	public void setFoundStat(String foundStat) {
		this.foundStat = foundStat;
	}

	public String getBaseStat() {
		return baseStat;
	}

	public void setBaseStat(String baseStat) {
		this.baseStat = baseStat;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	
	public Base() {
		// TODO Auto-generated constructor stub
	}
	
	
	
	@Override
	public String toString() {
		return "Base [baseId=" + baseId + ", baseName=" + baseName + ", baseType=" + baseType + ", found_type="
				+ found_type + ", dept=" + dept + ", users=" + users + ", foundSrc=" + foundSrc + ", foundBudget="
				+ foundBudget + ", foundProj=" + foundProj + ", foundDept=" + foundDept + ", foundStat=" + foundStat
				+ ", baseStat=" + baseStat + ", remark=" + remark + "]";
	}

  
    
    
}