package pdsu.dzyhp.bean;

public class Bat_mat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.bat_mat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String batMatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.bat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String batId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.mat_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String matName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.cate_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private Integer cateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.spec
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.price
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.amount
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.unit
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.remark
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.count
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private Double count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_mat.up_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String upTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.bat_mat_id
     *
     * @return the value of bat_mat.bat_mat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getBatMatId() {
        return batMatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.bat_mat_id
     *
     * @param batMatId the value for bat_mat.bat_mat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBatMatId(String batMatId) {
        this.batMatId = batMatId == null ? null : batMatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.bat_id
     *
     * @return the value of bat_mat.bat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getBatId() {
        return batId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.bat_id
     *
     * @param batId the value for bat_mat.bat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBatId(String batId) {
        this.batId = batId == null ? null : batId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.mat_name
     *
     * @return the value of bat_mat.mat_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getMatName() {
        return matName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.mat_name
     *
     * @param matName the value for bat_mat.mat_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setMatName(String matName) {
        this.matName = matName == null ? null : matName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.cate_id
     *
     * @return the value of bat_mat.cate_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Integer getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.cate_id
     *
     * @param cateId the value for bat_mat.cate_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setCateId(Integer cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.spec
     *
     * @return the value of bat_mat.spec
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.spec
     *
     * @param spec the value for bat_mat.spec
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.price
     *
     * @return the value of bat_mat.price
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.price
     *
     * @param price the value for bat_mat.price
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.amount
     *
     * @return the value of bat_mat.amount
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.amount
     *
     * @param amount the value for bat_mat.amount
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.unit
     *
     * @return the value of bat_mat.unit
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.unit
     *
     * @param unit the value for bat_mat.unit
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.remark
     *
     * @return the value of bat_mat.remark
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.remark
     *
     * @param remark the value for bat_mat.remark
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.count
     *
     * @return the value of bat_mat.count
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Double getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.count
     *
     * @param count the value for bat_mat.count
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setCount(Double count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.user_id
     *
     * @return the value of bat_mat.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.user_id
     *
     * @param userId the value for bat_mat.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_mat.up_time
     *
     * @return the value of bat_mat.up_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getUpTime() {
        return upTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_mat.up_time
     *
     * @param upTime the value for bat_mat.up_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setUpTime(String upTime) {
        this.upTime = upTime == null ? null : upTime.trim();
    }
}