package pdsu.dzyhp.bean;

public class Bat_info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_info.bat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String batId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_info.bat_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String batTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_info.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_info.plan_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_info.base_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private Integer baseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_info.bat_stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String batStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_info.check_user
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String checkUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bat_info.check_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String checkTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_info.bat_id
     *
     * @return the value of bat_info.bat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getBatId() {
        return batId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_info.bat_id
     *
     * @param batId the value for bat_info.bat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBatId(String batId) {
        this.batId = batId == null ? null : batId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_info.bat_time
     *
     * @return the value of bat_info.bat_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getBatTime() {
        return batTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_info.bat_time
     *
     * @param batTime the value for bat_info.bat_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBatTime(String batTime) {
        this.batTime = batTime == null ? null : batTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_info.user_id
     *
     * @return the value of bat_info.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_info.user_id
     *
     * @param userId the value for bat_info.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_info.plan_id
     *
     * @return the value of bat_info.plan_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_info.plan_id
     *
     * @param planId the value for bat_info.plan_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setPlanId(String planId) {
        this.planId = planId == null ? null : planId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_info.base_id
     *
     * @return the value of bat_info.base_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Integer getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_info.base_id
     *
     * @param baseId the value for bat_info.base_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBaseId(Integer baseId) {
        this.baseId = baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_info.bat_stat
     *
     * @return the value of bat_info.bat_stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getBatStat() {
        return batStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_info.bat_stat
     *
     * @param batStat the value for bat_info.bat_stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBatStat(String batStat) {
        this.batStat = batStat == null ? null : batStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_info.check_user
     *
     * @return the value of bat_info.check_user
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getCheckUser() {
        return checkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_info.check_user
     *
     * @param checkUser the value for bat_info.check_user
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setCheckUser(String checkUser) {
        this.checkUser = checkUser == null ? null : checkUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bat_info.check_time
     *
     * @return the value of bat_info.check_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bat_info.check_time
     *
     * @param checkTime the value for bat_info.check_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setCheckTime(String checkTime) {
        this.checkTime = checkTime == null ? null : checkTime.trim();
    }
}