package pdsu.dzyhp.bean;

public class Danger_degree {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_degree.degree_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private Integer degreeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_degree.degree_code
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String degreeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_degree.degree_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String degreeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column danger_degree.remark
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_degree.degree_id
     *
     * @return the value of danger_degree.degree_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Integer getDegreeId() {
        return degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_degree.degree_id
     *
     * @param degreeId the value for danger_degree.degree_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setDegreeId(Integer degreeId) {
        this.degreeId = degreeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_degree.degree_code
     *
     * @return the value of danger_degree.degree_code
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getDegreeCode() {
        return degreeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_degree.degree_code
     *
     * @param degreeCode the value for danger_degree.degree_code
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setDegreeCode(String degreeCode) {
        this.degreeCode = degreeCode == null ? null : degreeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_degree.degree_name
     *
     * @return the value of danger_degree.degree_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getDegreeName() {
        return degreeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_degree.degree_name
     *
     * @param degreeName the value for danger_degree.degree_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setDegreeName(String degreeName) {
        this.degreeName = degreeName == null ? null : degreeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column danger_degree.remark
     *
     * @return the value of danger_degree.remark
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column danger_degree.remark
     *
     * @param remark the value for danger_degree.remark
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}