package pdsu.dzyhp.bean;

public class Found_type {
   
    private Integer foundTypeId;

   
    private String foundType;

   
    private String foundDesc;

  
    private String stat;

   
    public Integer getFoundTypeId() {
        return foundTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_type.found_type_id
     *
     * @param foundTypeId the value for found_type.found_type_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setFoundTypeId(Integer foundTypeId) {
        this.foundTypeId = foundTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_type.found_type
     *
     * @return the value of found_type.found_type
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getFoundType() {
        return foundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_type.found_type
     *
     * @param foundType the value for found_type.found_type
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setFoundType(String foundType) {
        this.foundType = foundType == null ? null : foundType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_type.found_desc
     *
     * @return the value of found_type.found_desc
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getFoundDesc() {
        return foundDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_type.found_desc
     *
     * @param foundDesc the value for found_type.found_desc
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setFoundDesc(String foundDesc) {
        this.foundDesc = foundDesc == null ? null : foundDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column found_type.stat
     *
     * @return the value of found_type.stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getStat() {
        return stat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column found_type.stat
     *
     * @param stat the value for found_type.stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setStat(String stat) {
        this.stat = stat == null ? null : stat.trim();
    }
}