package pdsu.dzyhp.bean;

public class Plan_mat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_mat.plan_mat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String planMatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_mat.plan_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_mat.mat_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String matName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_mat.cate_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private Integer cateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_mat.spec
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String spec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_mat.price
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_mat.count
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private Double count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_mat.unit
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_mat.remark
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_mat.plan_mat_id
     *
     * @return the value of plan_mat.plan_mat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getPlanMatId() {
        return planMatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_mat.plan_mat_id
     *
     * @param planMatId the value for plan_mat.plan_mat_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setPlanMatId(String planMatId) {
        this.planMatId = planMatId == null ? null : planMatId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_mat.plan_id
     *
     * @return the value of plan_mat.plan_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_mat.plan_id
     *
     * @param planId the value for plan_mat.plan_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setPlanId(String planId) {
        this.planId = planId == null ? null : planId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_mat.mat_name
     *
     * @return the value of plan_mat.mat_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getMatName() {
        return matName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_mat.mat_name
     *
     * @param matName the value for plan_mat.mat_name
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setMatName(String matName) {
        this.matName = matName == null ? null : matName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_mat.cate_id
     *
     * @return the value of plan_mat.cate_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Integer getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_mat.cate_id
     *
     * @param cateId the value for plan_mat.cate_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setCateId(Integer cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_mat.spec
     *
     * @return the value of plan_mat.spec
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getSpec() {
        return spec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_mat.spec
     *
     * @param spec the value for plan_mat.spec
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setSpec(String spec) {
        this.spec = spec == null ? null : spec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_mat.price
     *
     * @return the value of plan_mat.price
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_mat.price
     *
     * @param price the value for plan_mat.price
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_mat.count
     *
     * @return the value of plan_mat.count
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Double getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_mat.count
     *
     * @param count the value for plan_mat.count
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setCount(Double count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_mat.unit
     *
     * @return the value of plan_mat.unit
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_mat.unit
     *
     * @param unit the value for plan_mat.unit
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_mat.remark
     *
     * @return the value of plan_mat.remark
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_mat.remark
     *
     * @param remark the value for plan_mat.remark
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}