package pdsu.dzyhp.bean;

public class Plan_info {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_info.plan_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String planId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_info.plan_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String planTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_info.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_info.base_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private Integer baseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_info.plan_stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String planStat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_info.check_user
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String checkUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plan_info.check_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    private String checkTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_info.plan_id
     *
     * @return the value of plan_info.plan_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getPlanId() {
        return planId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_info.plan_id
     *
     * @param planId the value for plan_info.plan_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setPlanId(String planId) {
        this.planId = planId == null ? null : planId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_info.plan_time
     *
     * @return the value of plan_info.plan_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getPlanTime() {
        return planTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_info.plan_time
     *
     * @param planTime the value for plan_info.plan_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setPlanTime(String planTime) {
        this.planTime = planTime == null ? null : planTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_info.user_id
     *
     * @return the value of plan_info.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_info.user_id
     *
     * @param userId the value for plan_info.user_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_info.base_id
     *
     * @return the value of plan_info.base_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public Integer getBaseId() {
        return baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_info.base_id
     *
     * @param baseId the value for plan_info.base_id
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setBaseId(Integer baseId) {
        this.baseId = baseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_info.plan_stat
     *
     * @return the value of plan_info.plan_stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getPlanStat() {
        return planStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_info.plan_stat
     *
     * @param planStat the value for plan_info.plan_stat
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setPlanStat(String planStat) {
        this.planStat = planStat == null ? null : planStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_info.check_user
     *
     * @return the value of plan_info.check_user
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getCheckUser() {
        return checkUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_info.check_user
     *
     * @param checkUser the value for plan_info.check_user
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setCheckUser(String checkUser) {
        this.checkUser = checkUser == null ? null : checkUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plan_info.check_time
     *
     * @return the value of plan_info.check_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public String getCheckTime() {
        return checkTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plan_info.check_time
     *
     * @param checkTime the value for plan_info.check_time
     *
     * @mbggenerated Tue Oct 08 21:15:41 GMT+08:00 2019
     */
    public void setCheckTime(String checkTime) {
        this.checkTime = checkTime == null ? null : checkTime.trim();
    }
}